#ifndef leaf_token_type_hpp
#define leaf_token_type_hpp

#include <ostream>
enum class TokenType {
    TOKEN_PRINT,
    TOKEN_PRINTLN,
    TOKEN_LET,
    TOKEN_CONST,
    TOKEN_IF,
    TOKEN_ELSEIF,
    TOKEN_ELSE,
    TOKEN_FOR,
    TOKEN_BREAK,
    TOKEN_CONTINUE,
    TOKEN_FUNC,
    TOKEN_CLASS,
    TOKEN_EXTENDS,
    TOKEN_THIS,
    TOKEN_SUPER,
    TOKEN_AND,
    TOKEN_OR,
    TOKEN_XOR,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_NIL,
    TOKEN_IDENTIFIER,
    TOKEN_STRING,
    TOKEN_NUMBER,

    TOKEN_PLUS,
    TOKEN_PLUS_PLUS,
    TOKEN_MINUS,
    TOKEN_MINUS_MINUS,
    TOKEN_STAR,
    TOKEN_SLASH,
    TOKEN_PERCENT,
    TOKEN_STAR_STAR,
    TOKEN_EQUAL,
    TOKEN_EQUAL_EQUAL,
    TOKEN_BANG,
    TOKEN_BANG_EQUAL,
    TOKEN_LESS,
    TOKEN_LESS_EQUAL,
    TOKEN_GREATER,
    TOKEN_GREATER_EQUAL,
    TOKEN_QUESTION,
    TOKEN_COLON,
    TOKEN_DOT,

    TOKEN_SEMICOLON,
    TOKEN_COMMA,
    TOKEN_LEFT_PAREN,
    TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE,
    TOKEN_RIGHT_BRACE,

    TOKEN_EOF,
};

auto operator << (std::ostream& stream, TokenType token) -> std::ostream&;

#endif
