gen_ast_classes: gen_ast_classes.cpp Tools.cpp
	c++ -std=c++23 -g -Wall -Wextra -Weffc++ -Werror -Wconversion -Wsign-conversion gen_ast_classes.cpp Tools.cpp -o gen_ast_classes

clean:
	rm -rf ./gen_ast_classes
